=== msertacturkel/JavaEE/XSL/samples2/AdresDefteri1.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--DTD generated by XMLSpy v2011 rel. 2 (http://www.altova.com)-->
<!ELEMENT Tel (#PCDATA)>
<!ELEMENT Sehir (#PCDATA)>
<!ELEMENT Posta-Kodu ((Posta, Kodu))>
<!ELEMENT Posta (#PCDATA)>
<!ELEMENT Mahalle (#PCDATA)>
<!ELEMENT Kodu (#PCDATA)>
<!ELEMENT Giris ((AdSoyad, Adres, Tel*))>
<!ELEMENT AdresDefteri ((Giris+))>
<!ELEMENT Adres ((Mahalle, Posta-Kodu?, Sehir))>
<!ELEMENT AdSoyad (#PCDATA)>

=== msertacturkel/JavaEE/XSL/samples2/AdresDefteri1.xml
<!DOCTYPE AdresDefteri SYSTEM "D:\ileriJavaKasim2013\xml\ornekler\AdresDefteri1.dtd">
<AdresDefteri>
	<Giris>
		<AdSoyad>Haka</AdSoyad>
		<Adres>
			<Mahalle>Mecidiyekoy</Mahalle>
			<Sehir>Istanbul</Sehir>
		</Adres>
		<Tel>11111</Tel>
		<Tel>1110</Tel>
		<Tel>222222</Tel>
	</Giris>
	<Giris>
		<AdSoyad>Murat</AdSoyad>
		<Adres>
			<Mahalle>Mecid</Mahalle>
			<Posta-Kodu>
				<Posta>www</Posta>
				<Kodu>222</Kodu>
			</Posta-Kodu>
			<Sehir>Ankara</Sehir>
		</Adres>
	</Giris>
	<Giris>
		<AdSoyad>Mustafa</AdSoyad>
		<Adres>
			<Mahalle>Bagcilar</Mahalle>
			<Posta-Kodu>
				<Posta>www</Posta>
				<Kodu>222</Kodu>
			</Posta-Kodu>
			<Sehir>Istanbul</Sehir>
		</Adres>
		<Tel>11111</Tel>
		<Tel>1110</Tel>
		<Tel>222222</Tel>
	</Giris>
</AdresDefteri>
