=== msertacturkel/JavaEE/XSL/samples2/AdresDefteri.dtd
<!ELEMENT AdresDefteri (Giris+)>
<!ELEMENT Giris (AdSoyad,Adres,Tel*) >
<!ELEMENT AdSoyad (#PCDATA) >
<!ELEMENT Adres (Mahalle,Posta-Kodu?,Sehir) >
<!ELEMENT Mahalle (#PCDATA) >
<!ELEMENT Posta-Kodu (#PCDATA)>
<!ELEMENT Sehir (#PCDATA)>
<!ELEMENT Tel (#PCDATA)>

=== msertacturkel/JavaEE/XSL/samples2/AdresDefteri.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2011 rel. 2 (http://www.altova.com) by cdernek (cdernek) -->
<!--Sample XML file generated by XMLSpy v2011 rel. 2 (http://www.altova.com)-->
<!DOCTYPE AdresDefteri SYSTEM "AdresDefteri.dtd">
<AdresDefteri>
	<Giris>
		<AdSoyad>Haka</AdSoyad>
		<Adres>
			<Mahalle>Mecidiyekoy</Mahalle>
			<Sehir>Istanbul</Sehir>
		</Adres>
		<Tel>11111</Tel>
		<Tel>1110</Tel>
		<Tel>222222</Tel>
	</Giris>
	<Giris>
		<AdSoyad>Murat</AdSoyad>
		<Adres>
			<Mahalle>Mecid</Mahalle>
			<Posta-Kodu>3333</Posta-Kodu>
			<Sehir>Ankara</Sehir>
		</Adres>
		<Tel>11111</Tel>
		<Tel>1112</Tel>
		<Tel>222222</Tel>
	</Giris>
	<Giris>
		<AdSoyad>Mustafa</AdSoyad>
		<Adres>
			<Mahalle>Bagcilar</Mahalle>
			<Posta-Kodu>2222</Posta-Kodu>
			<Sehir>Istanbul</Sehir>
		</Adres>
		<Tel>11111</Tel>
		<Tel>1110</Tel>
		<Tel>222222</Tel>
	</Giris>
</AdresDefteri>
