=== msertacturkel/JavaEE/XSL/samples2/Bolum1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--W3C Schema generated by XMLSpy v2011 rel. 2 (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="Soyad" type="xs:string"/>
	<xs:element name="telefon" type="xs:integer"/>
	<xs:element name="Adres">
		<xs:complexType>
			<xs:sequence>
				<xs:element type="xs:string" name="il"/>
				<xs:element type="xs:string" name="ilce"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Personel">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Ad" type="xs:string"/>
				<xs:element ref="Soyad"/>
				<xs:element ref="telefon" minOccurs="1" maxOccurs="2"/>
				<xs:element ref="Adres" minOccurs="0" maxOccurs="1"/>
			</xs:sequence>
			<xs:attribute name="cinsiyet" type="xs:string"/>
		</xs:complexType>
		
	</xs:element>
	<xs:element name="Bolum">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Personel" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== msertacturkel/JavaEE/XSL/samples2/Bolum.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2011 rel. 2 (http://www.altova.com) by cdernek (cdernek) -->
<Bolum xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///D:/ileriJavaKasim2013/xml/ornekler/Bolum1.xsd">
	<Personel cinsiyet="erkek">
		<Ad>Sertac</Ad>
		<Soyad>Turkel</Soyad>
		<telefon>1111222</telefon>
		<telefon>333</telefon>
		<Adres>
			<il>Istanbul</il>
			<ilce>Sisli</ilce>
		</Adres>
	</Personel>
	<Personel>
		<Ad>Eren</Ad>
		<Soyad>Yazici</Soyad>
		<telefon>2222</telefon>
	</Personel>
	<Personel>
		<Ad>Vahit</Ad>
		<Soyad>GÃ¼ler</Soyad>
		<telefon>444444</telefon>
	</Personel>
	<Personel>
		<Ad>Ali</Ad>
		<Soyad>Karaduran</Soyad>
		<telefon>222222</telefon>
	</Personel>
</Bolum>
